// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDN0jnZywjG_pXx_vC85H-wp2nil7X6g',
    appId: '1:355573449121:web:1506a502db009f68324be0',
    messagingSenderId: '355573449121',
    projectId: 'week5-auth-dashboard',
    authDomain: 'week5-auth-dashboard.firebaseapp.com',
    storageBucket: 'week5-auth-dashboard.firebasestorage.app',
    measurementId: 'G-0HHT43NYDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvogEwO3GEFBY2DoWrp0zEu9s6HezMmlk',
    appId: '1:355573449121:android:11ba57b426f1878a324be0',
    messagingSenderId: '355573449121',
    projectId: 'week5-auth-dashboard',
    storageBucket: 'week5-auth-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmouTfQRgxCmLTxvO5HWaFbIrXTzAJvs',
    appId: '1:355573449121:ios:9ab4eecd48546cc4324be0',
    messagingSenderId: '355573449121',
    projectId: 'week5-auth-dashboard',
    storageBucket: 'week5-auth-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.week5AuthDashboard',
  );
}
